In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, np.nan, 22, 28],
    'Salary': [50000, 54000, 58000, 52000, np.nan],
    'Department': ['HR', 'Finance', 'HR', 'IT', 'Finance']
}
df = pd.DataFrame(data)
print(df)

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  30.0  54000.0    Finance
2  Charlie   NaN  58000.0         HR
3    David  22.0  52000.0         IT
4      Eva  28.0      NaN    Finance

In [3]:
df.fillna(df['Age'].mean())

      Name    Age    Salary Department
0    Alice  25.00  50000.00         HR
1      Bob  30.00  54000.00    Finance
2  Charlie  26.25  58000.00         HR
3    David  22.00  52000.00         IT
4      Eva  28.00     26.25    Finance

In [4]:
df.fillna(df['Salary'].median())

      Name      Age   Salary Department
0    Alice     25.0  50000.0         HR
1      Bob     30.0  54000.0    Finance
2  Charlie  53000.0  58000.0         HR
3    David     22.0  52000.0         IT
4      Eva     28.0  53000.0    Finance

In [5]:
df[(df['Salary']>52000)]

      Name   Age   Salary Department
1      Bob  30.0  54000.0    Finance
2  Charlie   NaN  58000.0         HR

In [10]:
df.groupby('Department')['Salary'].mean()

Department
Finance    54000.0
HR         54000.0
IT         52000.0
Name: Salary, dtype: float64

In [11]:
df['Tax'] = df['Salary'] * 0.1

In [12]:
df

      Name   Age   Salary Department     Tax
0    Alice  25.0  50000.0         HR  5000.0
1      Bob  30.0  54000.0    Finance  5400.0
2  Charlie   NaN  58000.0         HR  5800.0
3    David  22.0  52000.0         IT  5200.0
4      Eva  28.0      NaN    Finance     NaN

In [17]:
max_salary_employee = df[df['Salary']== df['Salary'].max()]
print(max_salary_employee)

      Name  Age   Salary Department     Tax
2  Charlie  NaN  58000.0         HR  5800.0

In [21]:
# Patients table

patients_data = {
    'patient_id': [101, 102, 103, 104, 105],
    'name': ['Alice Chen', 'Bob Wilson', 'Carol Davis', 'David Kim', 'Eva Martinez'],
    'age': [32, 45, 28, 60, 38],
    'gender': ['F', 'M', 'F', 'M', 'F'],
    'blood_type': ['A+', 'O-', 'B+', 'AB+', 'A-'],
    'admission_date': ['2023-01-15', '2023-02-20', '2023-03-10', '2023-01-05', '2023-04-18']
}

# Doctors table

doctors_data = {
    'doctor_id': [1, 2, 3],
    'name': ['Dr. Smith', 'Dr. Johnson', 'Dr. Lee'],
    'specialization': ['Cardiology', 'Neurology', 'Pediatrics'],
    'years_experience': [10, 8, 5]
}

# Appointments table

appointments_data = {
    'appointment_id': [1001, 1002, 1003, 1004],
    'patient_id': [101, 102, 103, 105],
    'doctor_id': [1, 2, 3, 1],
    'date': ['2023-05-10', '2023-05-12', '2023-05-15', '2023-05-18'],
    'diagnosis': ['Hypertension', 'Migraine', 'Common Cold', 'Arrhythmia']
}

# Medications table

medications_data = {
    'medication_id': [501, 502, 503],
    'name': ['Lisinopril', 'Sumatriptan', 'Amoxicillin'],
    'category': ['Blood Pressure', 'Migraine', 'Antibiotic'],
    'cost': [20.50, 35.75, 8.99]
}

# Prescription table

prescriptions_data = {
    'prescription_id': [201, 202, 203],
    'appointment_id': [1001, 1002, 1004],
    'medication_id': [501, 502, 501],
    'dosage': ['10mg daily', '50mg as needed', '5mg twice daily']
}

patients_data_df = pd.DataFrame(patients_data)
doctors_data_df = pd.DataFrame(doctors_data)
appointments_data_df = pd.DataFrame(appointments_data)
medications_data_df = pd.DataFrame(medications_data)
prescriptions_data_df = pd.DataFrame(prescriptions_data)

In [19]:

inner_join_appointments = pd.merge(
    appointments_data_df, 
    patients_data_df, 
    on='patient_id', 
    how='inner'
)

In [20]:
inner_join_appointments

,appointment_id,patient_id,doctor_id,date,diagnosis,name,age,gender,blood_type,admission_date
0,1001,101,1,2023-05-10,Hypertension,Alice Chen,32,F,A+,2023-01-15
1,1002,102,2,2023-05-12,Migraine,Bob Wilson,45,M,O-,2023-02-20
2,1003,103,3,2023-05-15,Common Cold,Carol Davis,28,F,B+,2023-03-10
3,1004,105,1,2023-05-18,Arrhythmia,Eva Martinez,38,F,A-,2023-04-18

In [22]:
outer_join_medications = pd.merge(
    medications_data_df,
    prescriptions_data_df, 
    on='medication_id',             
    how='outer'
)

In [23]:
outer_join_medications

,medication_id,name,category,cost,prescription_id,appointment_id,dosage
0,501,Lisinopril,Blood Pressure,20.50,201.0,1001.0,10mg daily
1,501,Lisinopril,Blood Pressure,20.50,203.0,1004.0,5mg twice daily
2,502,Sumatriptan,Migraine,35.75,202.0,1002.0,50mg as needed
3,503,Amoxicillin,Antibiotic,8.99,NaN,NaN,NaN

In [26]:
employees_data = {
'id': [101, 102, 103, 104, 105],
'name': ['Aryam', 'Aavash', 'Bibek', 'Samyak', 'Sujan'],
'department': ['AI Engineer', 'Finance', 'Management',  'Finance', 'Marketing'],
'salary': [120000, 110000, 95000, 115000, 105000],
'experience': [5, 4, 7, 3, 2]
}

employees_data_df = pd.DataFrame(employees_data)

In [27]:
departments_data = {
    'id': [101, 102, 103, 104],
    'name': ['AI Engineer', 'Finance', 'Management', 'Marketing'],
    'location': ['Lalitpur', 'Imadol', 'Tanahu', 'Kathmandu'],
}

departments_data_df = pd.DataFrame(departments_data)

In [28]:
employees_data_df[employees_data_df['department'] == 'Finance']

    id    name department  salary  experience
1  102  Aavash    Finance  110000           4
3  104  Samyak    Finance  115000           3

In [29]:
employees_data_df[employees_data_df['experience'] > 3]

    id    name   department  salary  experience
0  101   Aryam  AI Engineer  120000           5
1  102  Aavash      Finance  110000           4
2  103   Bibek   Management   95000           7

In [34]:
employees_data_df.groupby('department')['salary'].mean()

department
AI Engineer    120000.0
Finance        112500.0
Management      95000.0
Marketing      105000.0
Name: salary, dtype: float64

In [36]:
above_avg = employees_data_df[employees_data_df['salary'] > employees_data_df['salary'].mean()]
above_avg

    id    name   department  salary  experience
0  101   Aryam  AI Engineer  120000           5
1  102  Aavash      Finance  110000           4
3  104  Samyak      Finance  115000           3

In [37]:
employees_data_df

    id    name   department  salary  experience
0  101   Aryam  AI Engineer  120000           5
1  102  Aavash      Finance  110000           4
2  103   Bibek   Management   95000           7
3  104  Samyak      Finance  115000           3
4  105   Sujan    Marketing  105000           2

In [44]:
merged_data = pd.merge(employees_data_df, departments_data_df, left_on='department',right_on='name',how='left')
merged_data

   id_x  name_x   department  salary  experience  id_y       name_y   location
0   101   Aryam  AI Engineer  120000           5   101  AI Engineer   Lalitpur
1   102  Aavash      Finance  110000           4   102      Finance     Imadol
2   103   Bibek   Management   95000           7   103   Management     Tanahu
3   104  Samyak      Finance  115000           3   102      Finance     Imadol
4   105   Sujan    Marketing  105000           2   104    Marketing  Kathmandu

In [45]:
# Students Table
students = pd.DataFrame({
    'student_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'class': ['10A', '10B', '10A', '10C', '10B']
})

# Scores Table
scores = pd.DataFrame({
    'student_id': [3, 4, 5, 6],
    'math_score': [88, 92, 75, 85],
    'science_score': [90, 85, 80, 70]
})

students_data_df = pd.DataFrame(students)
scores_data_df = pd.DataFrame(scores)

In [46]:
inner_join_students = pd.merge(students_data_df,  scores_data_df,  on='student_id',  how='inner')
inner_join_students

   student_id     name class  math_score  science_score
0           3  Charlie   10A          88             90
1           4    David   10C          92             85
2           5      Eve   10B          75             80

In [48]:
outer_join_students = pd.merge(students_data_df,  scores_data_df,  on='student_id',  how='outer')
outer_join_students

   student_id     name class  math_score  science_score
0           1    Alice   10A         NaN            NaN
1           2      Bob   10B         NaN            NaN
2           3  Charlie   10A        88.0           90.0
3           4    David   10C        92.0           85.0
4           5      Eve   10B        75.0           80.0
5           6      NaN   NaN        85.0           70.0

In [49]:
left_join_students = pd.merge(students_data_df,  scores_data_df,  on='student_id',  how='left')
left_join_students

   student_id     name class  math_score  science_score
0           1    Alice   10A         NaN            NaN
1           2      Bob   10B         NaN            NaN
2           3  Charlie   10A        88.0           90.0
3           4    David   10C        92.0           85.0
4           5      Eve   10B        75.0           80.0

In [50]:
right_join_students = pd.merge(students_data_df,  scores_data_df,  on='student_id',  how='right')
right_join_students

   student_id     name class  math_score  science_score
0           3  Charlie   10A          88             90
1           4    David   10C          92             85
2           5      Eve   10B          75             80
3           6      NaN   NaN          85             70

In [52]:
left_join_students_df = pd.merge(students_data_df, scores_data_df, on='student_id', how='left').fillna(0)
left_join_students_df

   student_id     name class  math_score  science_score
0           1    Alice   10A         0.0            0.0
1           2      Bob   10B         0.0            0.0
2           3  Charlie   10A        88.0           90.0
3           4    David   10C        92.0           85.0
4           5      Eve   10B        75.0           80.0

In [57]:
df = pd.merge(students, scores, on='student_id', how='left').fillna(0)
df['total_score'] = df['math_score'] + df['science_score']
print(df)

   student_id     name class  math_score  science_score  total_score
0           1    Alice   10A         0.0            0.0          0.0
1           2      Bob   10B         0.0            0.0          0.0
2           3  Charlie   10A        88.0           90.0        178.0
3           4    David   10C        92.0           85.0        177.0
4           5      Eve   10B        75.0           80.0        155.0