In [1]:
import pandas as pd

In [ ]:
# 1. EMPLOYEES Table
employees_data = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    'first_name': ['John', 'Sarah', 'Michael', 'Emma', 'David', 'Lisa', 'Robert', 'Anna', 'James', 'Maria', 'Kevin', 'Laura', 'Mark', 'Sophie', 'Alex'],
    'last_name': ['Smith', 'Johnson', 'Brown', 'Davis', 'Wilson', 'Miller', 'Jones', 'Garcia', 'Martinez', 'Rodriguez', 'Lee', 'Walker', 'Hall', 'Allen', 'Young'],
    'department_id': [1, 2, 1, 3, 2, 1, 4, 3, 2, 1, 4, 3, 2, 1, 5],
    'position': ['Manager', 'Analyst', 'Developer', 'Designer', 'Manager', 'Developer', 'Analyst', 'Designer', 'Developer', 'Manager', 'Analyst', 'Designer', 'Analyst', 'Developer', 'Manager'],
    'salary': [75000, 55000, 68000, 62000, 80000, 70000, 52000, 58000, 65000, 85000, 50000, 60000, 56000, 72000, 90000],
    'hire_date': ['2019-03-15', '2020-07-22', '2021-01-10', '2020-11-08', '2018-05-30', '2021-03-25', '2022-01-15', '2019-09-12', '2021-08-20', '2017-12-05', '2022-04-10', '2020-02-18', '2021-11-30', '2020-06-14', '2023-01-08'],
    'email': ['john.smith@company.com', 'sarah.johnson@company.com', 'michael.brown@company.com', 'emma.davis@company.com', 'david.wilson@company.com', 'lisa.miller@company.com', 'robert.jones@company.com', 'anna.garcia@company.com', 'james.martinez@company.com', 'maria.rodriguez@company.com', 'kevin.lee@company.com', 'laura.walker@company.com', 'mark.hall@company.com', 'sophie.allen@company.com', 'alex.young@company.com'],
    'phone': ['555-0101', '555-0102', '555-0103', '555-0104', '555-0105', '555-0106', '555-0107', '555-0108', '555-0109', '555-0110', '555-0111', '555-0112', '555-0113', '555-0114', '555-0115']
}

# 2. DEPARTMENTS Table
departments_data = {
    'department_id': [1, 2, 3, 4, 5, 6],
    'department_name': ['Engineering', 'Sales', 'Design', 'Marketing', 'Finance', 'HR'],
    'manager_id': [10, 5, 4, 7, 15, None],
    'budget': [500000, 300000, 200000, 250000, 180000, 150000],
    'location': ['New York', 'Chicago', 'San Francisco', 'Los Angeles', 'Boston', 'Seattle']
}

# 3. PROJECTS Table
projects_data = {
    'project_id': [101, 102, 103, 104, 105, 106, 107],
    'project_name': ['Website Redesign', 'Mobile App', 'Data Analytics', 'Marketing Campaign', 'ERP System', 'Customer Portal', 'AI Integration'],
    'department_id': [1, 1, 2, 4, 5, 1, 1],
    'start_date': ['2023-01-15', '2023-03-01', '2023-02-10', '2023-04-05', '2022-11-20', '2023-05-12', '2023-06-01'],
    'end_date': ['2023-06-30', '2023-08-15', '2023-07-20', '2023-09-30', '2024-02-28', '2023-10-15', '2024-01-31'],
    'budget': [150000, 200000, 100000, 80000, 300000, 120000, 250000],
    'status': ['Completed', 'In Progress', 'Completed', 'In Progress', 'In Progress', 'Planning', 'Planning']
}

#4. EMPLOYEE_PROJECTS Table
employee_projects_data = {
    'employee_id': [1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1, 2, 5],
    'project_id': [101, 102, 101, 102, 103, 104, 101, 102, 103, 101, 105, 104, 103, 102, 101, 105, 106, 107, 107],
    'role': ['Lead', 'Developer', 'Developer', 'Tester', 'Analyst', 'Lead', 'Developer', 'Analyst', 'Designer', 'Developer', 'Lead', 'Analyst', 'Designer', 'Analyst', 'Developer', 'Lead', 'Manager', 'Developer', 'Manager'],
    'hours_allocated': [40, 35, 30, 20, 40, 40, 25, 30, 35, 20, 40, 25, 30, 20, 15, 40, 30, 35, 25]
}

# Create DataFrames
employees_data_df = pd.DataFrame(employees_data)
departments_data_df = pd.DataFrame(departments_data) 
projects_data_df = pd.DataFrame(projects_data)
employee_projects_data = pd.DataFrame(employee_projects_data)

In [7]:
employees_data_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [ ]:
employees_data_df[['first_name','last_name']] #Select first name and last name from employee_df table

   first_name  last_name
0        John      Smith
1       Sarah    Johnson
2     Michael      Brown
3        Emma      Davis
4       David     Wilson
5        Lisa     Miller
6      Robert      Jones
7        Anna     Garcia
8       James   Martinez
9       Maria  Rodriguez
10      Kevin        Lee
11      Laura     Walker
12       Mark       Hall
13     Sophie      Allen
14       Alex      Young

In [ ]:
employees_data_df['department_id'].unique() #select distinct department

array([1, 2, 3, 4, 5])

In [11]:
employees_data_df.rename(columns={'first_name':'Pahilo_nam','last_name':'Pachilo_nam'}) #rename

,employee_id,Pahilo_nam,Pachilo_nam,department_id,position,salary,hire_date,email,phone
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [13]:
# Where Statement

employees_data_df[employees_data_df['salary'] > 70000]

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [ ]:
employees_data_df[employees_data_df['position'] == 'Analyst']

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113

In [ ]:
employees_data_df['hire_date'] = pd.to_datetime(employees_data_df['hire_date']) # filtering object changed to datetime

In [ ]:
employees_data_df[employees_data_df['hire_date'] > '2020-01-01'] #if not this wont work (not filtered then)

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [18]:
employees_data_df[(employees_data_df['position'] == 'Developer') & (employees_data_df['salary'] > 60000)]

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114

In [ ]:
employees_data_df[employees_data_df['first_name'].str.startswith('Mich')] # ILIKE 'STR = String'

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103

In [ ]:
employees_data_df[employees_data_df['position'].isin (['Developer', 'Designer'])] #isin le chai developer ra designer kun kun xa tesko row print garxa

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114

In [ ]:
employees_data_df.groupby('position').size().reset_index(name='employee_count') # count group by

    position  employee_count
0    Analyst               4
1   Designer               3
2  Developer               4
3    Manager               4

In [23]:
employees_data_df.dtypes

employee_id               int64
first_name               object
last_name                object
department_id             int64
position                 object
salary                    int64
hire_date        datetime64[ns]
email                    object
phone                    object
dtype: object

In [ ]:
employees_data_df.groupby('department_id')['salary'].mean().reset_index() #reset_index garena vane 0 1 2 3 .. aaudaina arkai aauxa

   department_id   salary
0              1  74000.0
1              2  64000.0
2              3  60000.0
3              4  51000.0
4              5  90000.0

In [ ]:
employees_data_df.sort_values(by='last_name', ascending=True)

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [26]:
employees_data_df.sort_values(by=['salary','last_name'], ascending=[True, False])

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [ ]:
employees_data_df.sort_values(by=employees_data_df.columns[2]) #using index 0,1,2.. and sorting

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [ ]:
# JOINS

merged_df = pd.merge(employees_data_df, departments_data_df, on='department_id', how='inner') # Inner join, department id anusar join vako xa employee ra department ko

In [29]:
merged_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,department_name,manager_id,budget,location
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,Engineering,10.0,500000,New York
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,Sales,5.0,300000,Chicago
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,Engineering,10.0,500000,New York
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,Design,4.0,200000,San Francisco
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,Sales,5.0,300000,Chicago
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,Engineering,10.0,500000,New York
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,Marketing,7.0,250000,Los Angeles
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,Design,4.0,200000,San Francisco
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,Sales,5.0,300000,Chicago
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,Engineering,10.0,500000,New York
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,Marketing,7.0,250000,Los Angeles
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,Design,4.0,200000,San Francisco
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,Sales,5.0,300000,Chicago
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,Engineering,10.0,500000,New York
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,Finance,15.0,180000,Boston

In [30]:
departments_data_df

   department_id department_name  manager_id  budget       location
0              1     Engineering        10.0  500000       New York
1              2           Sales         5.0  300000        Chicago
2              3          Design         4.0  200000  San Francisco
3              4       Marketing         7.0  250000    Los Angeles
4              5         Finance        15.0  180000         Boston
5              6              HR         NaN  150000        Seattle

In [31]:
merged_df = pd.merge(employees_data_df, departments_data_df, on='department_id', how='left')

In [32]:
merged_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,department_name,manager_id,budget,location
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,Engineering,10.0,500000,New York
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,Sales,5.0,300000,Chicago
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,Engineering,10.0,500000,New York
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,Design,4.0,200000,San Francisco
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,Sales,5.0,300000,Chicago
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,Engineering,10.0,500000,New York
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,Marketing,7.0,250000,Los Angeles
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,Design,4.0,200000,San Francisco
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,Sales,5.0,300000,Chicago
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,Engineering,10.0,500000,New York
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,Marketing,7.0,250000,Los Angeles
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,Design,4.0,200000,San Francisco
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,Sales,5.0,300000,Chicago
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,Engineering,10.0,500000,New York
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,Finance,15.0,180000,Boston

In [33]:
merged_df = pd.merge(employees_data_df, departments_data_df, on='department_id', how='outer')
merged_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,department_name,manager_id,budget,location
0,1.0,John,Smith,1,Manager,75000.0,2019-03-15,john.smith@company.com,555-0101,Engineering,10.0,500000,New York
1,3.0,Michael,Brown,1,Developer,68000.0,2021-01-10,michael.brown@company.com,555-0103,Engineering,10.0,500000,New York
2,6.0,Lisa,Miller,1,Developer,70000.0,2021-03-25,lisa.miller@company.com,555-0106,Engineering,10.0,500000,New York
3,10.0,Maria,Rodriguez,1,Manager,85000.0,2017-12-05,maria.rodriguez@company.com,555-0110,Engineering,10.0,500000,New York
4,14.0,Sophie,Allen,1,Developer,72000.0,2020-06-14,sophie.allen@company.com,555-0114,Engineering,10.0,500000,New York
5,2.0,Sarah,Johnson,2,Analyst,55000.0,2020-07-22,sarah.johnson@company.com,555-0102,Sales,5.0,300000,Chicago
6,5.0,David,Wilson,2,Manager,80000.0,2018-05-30,david.wilson@company.com,555-0105,Sales,5.0,300000,Chicago
7,9.0,James,Martinez,2,Developer,65000.0,2021-08-20,james.martinez@company.com,555-0109,Sales,5.0,300000,Chicago
8,13.0,Mark,Hall,2,Analyst,56000.0,2021-11-30,mark.hall@company.com,555-0113,Sales,5.0,300000,Chicago
9,4.0,Emma,Davis,3,Designer,62000.0,2020-11-08,emma.davis@company.com,555-0104,Design,4.0,200000,San Francisco
10,8.0,Anna,Garcia,3,Designer,58000.0,2019-09-12,anna.garcia@company.com,555-0108,Design,4.0,200000,San Francisco
11,12.0,Laura,Walker,3,Designer,60000.0,2020-02-18,laura.walker@company.com,555-0112,Design,4.0,200000,San Francisco
12,7.0,Robert,Jones,4,Analyst,52000.0,2022-01-15,robert.jones@company.com,555-0107,Marketing,7.0,250000,Los Angeles
13,11.0,Kevin,Lee,4,Analyst,50000.0,2022-04-10,kevin.lee@company.com,555-0111,Marketing,7.0,250000,Los Angeles
14,15.0,Alex,Young,5,Manager,90000.0,2023-01-08,alex.young@company.com,555-0115,Finance,15.0,180000,Boston
15,NaN,NaN,NaN,6,NaN,NaN,NaT,NaN,NaN,HR,NaN,150000,Seattle

In [34]:
merged_df = pd.merge(employees_data_df, projects_data_df, on='department_id', how='inner')
merged_outer_df = pd.merge(employees_data_df, projects_data_df, on='department_id', how='outer')
merged_left_df = pd.merge(employees_data_df, projects_data_df, on='department_id', how='left')
merged_right_df = pd.merge(employees_data_df, projects_data_df, on='department_id', how='right')

In [35]:
merged_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,project_id,project_name,start_date,end_date,budget,status
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
1,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
2,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
3,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
4,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,103,Data Analytics,2023-02-10,2023-07-20,100000,Completed
5,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
6,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
7,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
8,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
9,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,103,Data Analytics,2023-02-10,2023-07-20,100000,Completed
10,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
11,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
12,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
13,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
14,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,104,Marketing Campaign,2023-04-05,2023-09-30,80000,In Progress
15,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,103,Data Analytics,2023-02-10,2023-07-20,100000,Completed
16,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
17,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
18,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
19,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
20,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,104,Marketing Campaign,2023-04-05,2023-09-30,80000,In Progress
21,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,103,Data Analytics,2023-02-10,2023-07-20,100000,Completed
22,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
23,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
24,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
25,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
26,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,105,ERP System,2022-11-20,2024-02-28,300000,In Progress

In [36]:
merged_left_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,project_id,project_name,start_date,end_date,budget,status
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
1,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
2,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
3,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
4,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,103.0,Data Analytics,2023-02-10,2023-07-20,100000.0,Completed
5,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
6,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
7,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
8,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
9,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,NaN,NaN,NaN,NaN,NaN,NaN
10,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,103.0,Data Analytics,2023-02-10,2023-07-20,100000.0,Completed
11,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
12,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
13,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
14,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
15,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,104.0,Marketing Campaign,2023-04-05,2023-09-30,80000.0,In Progress
16,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,NaN,NaN,NaN,NaN,NaN,NaN
17,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,103.0,Data Analytics,2023-02-10,2023-07-20,100000.0,Completed
18,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
19,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
20,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
21,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
22,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,104.0,Marketing Campaign,2023-04-05,2023-09-30,80000.0,In Progress
23,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,NaN,NaN,NaN,NaN,NaN,NaN
24,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,103.0,Data Analytics,2023-02-10,2023-07-20,100000.0,Completed
25,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
26,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
27,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
28,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
29,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,105.0,ERP System,2022-11-20,2024-02-28,300000.0,In Progress

In [37]:
merged_outer_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,project_id,project_name,start_date,end_date,budget,status
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
1,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
2,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
3,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
4,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
5,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
6,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
7,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
8,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
9,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
10,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
11,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
12,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
13,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
14,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
15,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
16,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,101.0,Website Redesign,2023-01-15,2023-06-30,150000.0,Completed
17,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,102.0,Mobile App,2023-03-01,2023-08-15,200000.0,In Progress
18,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,106.0,Customer Portal,2023-05-12,2023-10-15,120000.0,Planning
19,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,107.0,AI Integration,2023-06-01,2024-01-31,250000.0,Planning
20,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,103.0,Data Analytics,2023-02-10,2023-07-20,100000.0,Completed
21,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,103.0,Data Analytics,2023-02-10,2023-07-20,100000.0,Completed
22,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,103.0,Data Analytics,2023-02-10,2023-07-20,100000.0,Completed
23,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,103.0,Data Analytics,2023-02-10,2023-07-20,100000.0,Completed
24,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,NaN,NaN,NaN,NaN,NaN,NaN
25,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,NaN,NaN,NaN,NaN,NaN,NaN
26,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,NaN,NaN,NaN,NaN,NaN,NaN
27,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,104.0,Marketing Campaign,2023-04-05,2023-09-30,80000.0,In Progress
28,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,104.0,Marketing Campaign,2023-04-05,2023-09-30,80000.0,In Progress
29,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,105.0,ERP System,2022-11-20,2024-02-28,300000.0,In Progress

In [38]:
merged_right_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,project_id,project_name,start_date,end_date,budget,status
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
1,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
2,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
3,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
4,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,101,Website Redesign,2023-01-15,2023-06-30,150000,Completed
5,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
6,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
7,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
8,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
9,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,102,Mobile App,2023-03-01,2023-08-15,200000,In Progress
10,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,103,Data Analytics,2023-02-10,2023-07-20,100000,Completed
11,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,103,Data Analytics,2023-02-10,2023-07-20,100000,Completed
12,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,103,Data Analytics,2023-02-10,2023-07-20,100000,Completed
13,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,103,Data Analytics,2023-02-10,2023-07-20,100000,Completed
14,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,104,Marketing Campaign,2023-04-05,2023-09-30,80000,In Progress
15,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,104,Marketing Campaign,2023-04-05,2023-09-30,80000,In Progress
16,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,105,ERP System,2022-11-20,2024-02-28,300000,In Progress
17,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
18,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
19,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
20,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
21,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,106,Customer Portal,2023-05-12,2023-10-15,120000,Planning
22,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
23,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
24,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
25,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,107,AI Integration,2023-06-01,2024-01-31,250000,Planning
26,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,107,AI Integration,2023-06-01,2024-01-31,250000,Planning

In [39]:
projects_data_df

,project_id,project_name,department_id,start_date,end_date,budget,status
0,101,Website Redesign,1,2023-01-15,2023-06-30,150000,Completed
1,102,Mobile App,1,2023-03-01,2023-08-15,200000,In Progress
2,103,Data Analytics,2,2023-02-10,2023-07-20,100000,Completed
3,104,Marketing Campaign,4,2023-04-05,2023-09-30,80000,In Progress
4,105,ERP System,5,2022-11-20,2024-02-28,300000,In Progress
5,106,Customer Portal,1,2023-05-12,2023-10-15,120000,Planning
6,107,AI Integration,1,2023-06-01,2024-01-31,250000,Planning