In [ ]:
import pandas as pd
import numpy as np
data = {
    "name": ['Aryam','Aavash','Nahakul','Bibek','Samyak','Sujan'], #NAN in each value np.nan 
    "age": [20,30,np.nan,40,np.nan,50],
    "city": ['Lalitpur', 'Bhaktapur', 'Kathmandu', 'Tanahun','Imadol','Koteshwor'],
    "salary": [10000,20000,np.nan,30000,40000,np.nan]
}
df = pd.DataFrame(data)
df

      name   age       city   salary
0    Aryam  20.0   Lalitpur  10000.0
1   Aavash  30.0  Bhaktapur  20000.0
2  Nahakul   NaN  Kathmandu      NaN
3    Bibek  40.0    Tanahun  30000.0
4   Samyak   NaN     Imadol  40000.0
5    Sujan  50.0  Koteshwor      NaN

In [ ]:
df.isnull() #in which rows value is null

    name    age   city  salary
0  False  False  False   False
1  False  False  False   False
2  False   True  False    True
3  False  False  False   False
4  False   True  False   False
5  False  False  False    True

In [5]:
df.isnull().sum()

name      0
age       2
city      0
salary    2
dtype: int64

In [ ]:
df.notnull() #in which rows values are not null

   name    age  city  salary
0  True   True  True    True
1  True   True  True    True
2  True  False  True   False
3  True   True  True    True
4  True  False  True    True
5  True   True  True   False

In [7]:
df.notnull().sum()

name      6
age       4
city      6
salary    4
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   age     4 non-null      float64
 2   city    6 non-null      object
 3   salary  4 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [9]:
df

      name   age       city   salary
0    Aryam  20.0   Lalitpur  10000.0
1   Aavash  30.0  Bhaktapur  20000.0
2  Nahakul   NaN  Kathmandu      NaN
3    Bibek  40.0    Tanahun  30000.0
4   Samyak   NaN     Imadol  40000.0
5    Sujan  50.0  Koteshwor      NaN

In [ ]:
df.dropna()#ROWS are removed which contained null values

     name   age       city   salary
0   Aryam  20.0   Lalitpur  10000.0
1  Aavash  30.0  Bhaktapur  20000.0
3   Bibek  40.0    Tanahun  30000.0

In [11]:
df.dropna(inplace=True)

In [12]:
df

     name   age       city   salary
0   Aryam  20.0   Lalitpur  10000.0
1  Aavash  30.0  Bhaktapur  20000.0
3   Bibek  40.0    Tanahun  30000.0

In [19]:
import pandas as pd
import numpy as np
data = {
    "name": ['Aryam','Aavash','Nahakul','Bibek','Samyak','Sujan','Aryam'], 
    "age": [20,30,np.nan,40,np.nan,50,20],
    "city": ['Lalitpur', 'Bhaktapur', 'Kathmandu', 'Tanahun','Imadol','Koteshwor','Lalitpur'],
    "salary": [10000,20000,np.nan,30000,40000,np.nan,10000]
}
df = pd.DataFrame(data)
df

      name   age       city   salary
0    Aryam  20.0   Lalitpur  10000.0
1   Aavash  30.0  Bhaktapur  20000.0
2  Nahakul   NaN  Kathmandu      NaN
3    Bibek  40.0    Tanahun  30000.0
4   Samyak   NaN     Imadol  40000.0
5    Sujan  50.0  Koteshwor      NaN
6    Aryam  20.0   Lalitpur  10000.0

In [ ]:
df.duplicated() #Check duplicate

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
df.drop_duplicates(inplace=True) #delete duplicate

In [15]:
df

      name   age       city   salary
0    Aryam  20.0   Lalitpur  10000.0
1   Aavash  30.0  Bhaktapur  20000.0
2  Nahakul   NaN  Kathmandu      NaN
3    Bibek  40.0    Tanahun  30000.0
4   Samyak   NaN     Imadol  40000.0
5    Sujan  50.0  Koteshwor      NaN

In [ ]:
df.dropna(subset=['salary']) #particular

     name   age       city   salary
0   Aryam  20.0   Lalitpur  10000.0
1  Aavash  30.0  Bhaktapur  20000.0
3   Bibek  40.0    Tanahun  30000.0
4  Samyak   NaN     Imadol  40000.0

In [ ]:
#Box Plot
data = {
    "student": ['Aryam','Aavash','Nahakul','Bibek','Samyak','Sujan','Aryam'],
    "marks": [85,90,78,400,88,0,95]
}

df = pd.DataFrame(data)
df

   student  marks
0    Aryam     85
1   Aavash     90
2  Nahakul     78
3    Bibek    400
4   Samyak     88
5    Sujan    900
6    Aryam     95

In [ ]:
Q1 = df['marks'].quantile(0.25)
Q3 = df['marks'].quantile(0.75)
IQR = Q3 - Q1

print (Q1, Q3, IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier = df[(df['marks'] < 0) | (df['marks'] > 100)]  #Replace the value to 0 = lower_bound and 100 = upper_bound

86.5 247.5 161.0

In [28]:
outlier

  student  marks
3   Bibek    400
5   Sujan    900

In [29]:
# Imputing Values
data = {
    "student": ['Aryam','Aavash','Nahakul','Bibek','Samyak','Sujan','Aryam'],
    "marks": [85,90,np.nan,np.nan,88,np.nan,95]
}

df = pd.DataFrame(data)
df

   student  marks
0    Aryam   85.0
1   Aavash   90.0
2  Nahakul    NaN
3    Bibek    NaN
4   Samyak   88.0
5    Sujan    NaN
6    Aryam   95.0

In [ ]:
df.fillna(df['marks'].mean()) #calculates mean and adds it on null values

   student  marks
0    Aryam   85.0
1   Aavash   90.0
2  Nahakul   89.5
3    Bibek   89.5
4   Samyak   88.0
5    Sujan   89.5
6    Aryam   95.0

In [31]:
# Imputing Values
data = {
    "student": ['Aryam','Aavash','Nahakul','Bibek','Samyak','Sujan','Aryam'],
    "marks": [100,90,np.nan,np.nan,88,np.nan,95]
}

df = pd.DataFrame(data)
df

   student  marks
0    Aryam  100.0
1   Aavash   90.0
2  Nahakul    NaN
3    Bibek    NaN
4   Samyak   88.0
5    Sujan    NaN
6    Aryam   95.0

In [33]:
df.fillna(df['marks'].median())

   student  marks
0    Aryam  100.0
1   Aavash   90.0
2  Nahakul   92.5
3    Bibek   92.5
4   Samyak   88.0
5    Sujan   92.5
6    Aryam   95.0