In [2]:
# Broadcasting: It allows us to add a vector to each row of the matrix
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])

vector = np.array([10, 20, 30])

result = matrix + vector

print("Result:")
print(result)

Result:
[[11 22 33]
 [14 25 36]]

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.mean())
print(arr.max())
print(arr.sum())
print(arr.min())
print(arr.var())
print(arr.std())

5.5
10
55
1
8.25
2.8722813232690143

In [5]:
arr = np.random.randint(1, 10, size=(3, 4))
print("Random Array:")
print(arr)

Random Array:
[[3 3 3 9]
 [3 2 4 4]
 [8 1 6 2]]

In [ ]:
mean_value = arr.mean()
print("Mean of the array:")
print(mean_value)

4.0

In [7]:
reshaped_arr = arr.reshape(2, 6)
print("Reshaped Array:")
print(reshaped_arr)

Reshaped Array:
[[3 3 3 9 3 2]
 [4 4 8 1 6 2]]

In [8]:
broadcasted_arr = arr + np.array([10, 20, 30, 40])
print("Broadcasted Array:")
print(broadcasted_arr)

Broadcasted Array:
[[13 23 33 49]
 [13 22 34 44]
 [18 21 36 42]]

In [9]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie','David', 'Eve'],
    'Age': [25, 30, np.nan, 28, 22],
    'Salary': [50000, 60000, 70000, np.nan, 45000]
}
df = pd.DataFrame(data)
df

      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie   NaN  70000.0
3    David  28.0      NaN
4      Eve  22.0  45000.0

In [ ]:
print("\nSummary Statistics:")
print(df.describe())  # Summary statistics of the DataFrame

Summary Statistics:
         Age        Salary
count   4.00      4.000000
mean   26.25  56250.000000
std     3.50  11086.778913
min    22.00  45000.000000
25%    24.25  48750.000000
50%    26.50  55000.000000
75%    28.50  62500.000000
max    30.00  70000.000000

In [11]:
df['Age'] = df['Age'].fillna(df['Age'].median())

df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

print("\nDataFrame after filling missing values:")
print(df)

DataFrame after filling missing values:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie  26.5  70000.0
3    David  28.0  56250.0
4      Eve  22.0  45000.0

In [12]:
older_people_than_25 = df[df['Age'] > 25]
older_people_than_25

      Name   Age   Salary
1      Bob  30.0  60000.0
2  Charlie  26.5  70000.0
3    David  28.0  56250.0

In [13]:
df['Department'] = ['HR', 'IT', 'IT', 'HR', 'Finance']
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  30.0  60000.0         IT
2  Charlie  26.5  70000.0         IT
3    David  28.0  56250.0         HR
4      Eve  22.0  45000.0    Finance

In [14]:
salary = df.groupby('Department')['Salary'].agg(['mean', 'count'])
salary

               mean  count
Department
Finance     45000.0      1
HR          53125.0      2
IT          65000.0      2

In [20]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1

print(f'Q1: {Q1}, Q3: {Q3}, IQR: {IQR}')

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower_bound) | (df['Salary'] > upper_bound)]

print("\nOutliers in Salary:")
outliers[['Name', 'Salary']] if not outliers.empty else "No outliers found."

Q1: 50000.0, Q3: 60000.0, IQR: 10000.0

Outliers in Salary:

'No outliers found.'